version: "3.8"
services:
  finalproject:
    image: schbros/finalproject1:1.0.0
    build: .
    container_name: finalprojectcontainer
    ports: 
      - "80:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    
